import i18n from 'i18next';

export const hobbyOptions = [
    // Спорт і активність
    { value: 1, get label() { return i18n.t('step2.hobbies_options.1', 'Фітнес / Тренажерний зал'); } },
    { value: 2, get label() { return i18n.t('step2.hobbies_options.2', 'Біг / Легка атлетика'); } },
    { value: 3, get label() { return i18n.t('step2.hobbies_options.3', 'Йога / Медитація'); } },
    { value: 4, get label() { return i18n.t('step2.hobbies_options.4', 'Велоспорт'); } },
    { value: 5, get label() { return i18n.t('step2.hobbies_options.5', 'Командні види спорту'); } },
    { value: 6, get label() { return i18n.t('step2.hobbies_options.6', 'Бойові мистецтва'); } },
    { value: 7, get label() { return i18n.t('step2.hobbies_options.7', 'Походи / Гори'); } },
    { value: 26, get label() { return i18n.t('step2.hobbies_options.26', 'Плавання / Аквапарки'); } },
    { value: 27, get label() { return i18n.t('step2.hobbies_options.27', 'Танці'); } },
    { value: 28, get label() { return i18n.t('step2.hobbies_options.28', 'Скейтбординг / Лонгбординг'); } },
    { value: 29, get label() { return i18n.t('step2.hobbies_options.29', 'Лижі / Сноубординг'); } },
    { value: 30, get label() { return i18n.t('step2.hobbies_options.30', 'Скелелазіння / Боулдеринг'); } },
    { value: 31, get label() { return i18n.t('step2.hobbies_options.31', 'Стрільба з лука'); } },
    { value: 32, get label() { return i18n.t('step2.hobbies_options.32', 'Каякінг / Парусний спорт'); } },
    { value: 33, get label() { return i18n.t('step2.hobbies_options.33', 'Серфінг / Кайт'); } },
    // Творчість та мистецтво
    { value: 8, get label() { return i18n.t('step2.hobbies_options.8', 'Музика / Гра на інструментах'); } },
    { value: 9, get label() { return i18n.t('step2.hobbies_options.9', 'Фотографія / Відео'); } },
    { value: 10, get label() { return i18n.t('step2.hobbies_options.10', 'Малювання / Дизайн'); } },
    { value: 11, get label() { return i18n.t('step2.hobbies_options.11', 'Рукоділля / DIY'); } },
    { value: 12, get label() { return i18n.t('step2.hobbies_options.12', 'Письменництво / Блогінг'); } },
    { value: 34, get label() { return i18n.t('step2.hobbies_options.34', 'Кераміка / Гончарство'); } },
    { value: 35, get label() { return i18n.t('step2.hobbies_options.35', '3D / Цифрове мистецтво'); } },
    { value: 36, get label() { return i18n.t('step2.hobbies_options.36', 'Театр / Акторська майстерність'); } },
    { value: 37, get label() { return i18n.t('step2.hobbies_options.37', 'Вокал / Спів'); } },
    { value: 38, get label() { return i18n.t('step2.hobbies_options.38', 'DJ / Продюсування музики'); } },
    { value: 39, get label() { return i18n.t('step2.hobbies_options.39', 'Татуювання / Боді-арт'); } },
    { value: 40, get label() { return i18n.t('step2.hobbies_options.40', 'Каліграфія'); } },
    // Розваги та гік-культура
    { value: 13, get label() { return i18n.t('step2.hobbies_options.13', 'Відеоігри'); } },
    { value: 14, get label() { return i18n.t('step2.hobbies_options.14', 'Настільні ігри'); } },
    { value: 15, get label() { return i18n.t('step2.hobbies_options.15', 'Кіно та Серіали'); } },
    { value: 16, get label() { return i18n.t('step2.hobbies_options.16', 'Аніме / Манга'); } },
    { value: 17, get label() { return i18n.t('step2.hobbies_options.17', 'Книги / Література'); } },
    { value: 41, get label() { return i18n.t('step2.hobbies_options.41', 'D&D / Рольові ігри'); } },
    { value: 42, get label() { return i18n.t('step2.hobbies_options.42', 'Косплей'); } },
    { value: 43, get label() { return i18n.t('step2.hobbies_options.43', 'Подкасти'); } },
    { value: 44, get label() { return i18n.t('step2.hobbies_options.44', 'Стримінг / Контент-кріейтинг'); } },
    { value: 45, get label() { return i18n.t('step2.hobbies_options.45', 'Колекціонування (марки, монети, фігурки)'); } },
    { value: 46, get label() { return i18n.t('step2.hobbies_options.46', 'Караоке'); } },
    // Стиль життя та інше
    { value: 18, get label() { return i18n.t('step2.hobbies_options.18', 'Кулінарія / Випічка'); } },
    { value: 19, get label() { return i18n.t('step2.hobbies_options.19', 'Подорожі / Туризм'); } },
    { value: 20, get label() { return i18n.t('step2.hobbies_options.20', 'Домашні тварини'); } },
    { value: 21, get label() { return i18n.t('step2.hobbies_options.21', 'Кімнатні рослини'); } },
    { value: 22, get label() { return i18n.t('step2.hobbies_options.22', 'Волонтерство'); } },
    { value: 23, get label() { return i18n.t('step2.hobbies_options.23', 'Технології / Програмування'); } },
    { value: 24, get label() { return i18n.t('step2.hobbies_options.24', 'Вивчення мов'); } },
    { value: 25, get label() { return i18n.t('step2.hobbies_options.25', 'Мода / Стиль'); } },
    { value: 47, get label() { return i18n.t('step2.hobbies_options.47', 'Кава / Кавова культура'); } },
    { value: 48, get label() { return i18n.t('step2.hobbies_options.48', 'Чай / Чайна культура'); } },
    { value: 49, get label() { return i18n.t('step2.hobbies_options.49', 'Вино / Енологія'); } },
    { value: 50, get label() { return i18n.t('step2.hobbies_options.50', 'Городництво / Сад'); } },
    { value: 51, get label() { return i18n.t('step2.hobbies_options.51', 'Психологія / Саморозвиток'); } },
    { value: 52, get label() { return i18n.t('step2.hobbies_options.52', 'Інвестиції / Фінанси'); } },
];
