# Generated by Django 6.0.4 on 2026-05-06 14:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_expand_hobbies_and_custom_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='embedding_hobbies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='embedding_schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='embedding_vibe',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parsed_sleep_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parsed_wake_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userhousing',
            name='destination',
            field=models.IntegerField(blank=True, choices=[(1, 'Київ'), (2, 'Львів'), (3, 'Харків'), (4, 'Одеса'), (5, 'Дніпро'), (6, 'Запоріжжя'), (7, 'Вінниця'), (8, 'Черкаси'), (9, 'Івано-Франківськ'), (10, 'Тернопіль'), (11, 'Рівне'), (12, 'Житомир'), (13, 'Суми'), (14, 'Полтава'), (15, 'Чернігів'), (16, 'Кропивницький'), (17, 'Луцьк'), (18, 'Хмельницький'), (19, 'Миколаїв'), (20, 'Чернівці'), (21, 'Ужгород'), (22, 'Берегове'), (23, "Кам'янець-Подільський"), (24, "Кам'янське"), (25, 'Біла Церква'), (26, 'Бровари'), (27, 'Херсон'), (28, 'Мукачево'), (29, 'Кременчук'), (30, 'Конотоп'), (31, 'Умань'), (32, 'Яремче')], null=True),
        ),
        migrations.AlterField(
            model_name='userhousing',
            name='preferred_districts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'Голосіївський'), (2, 'Дарницький'), (3, 'Деснянський'), (4, 'Дніпровський'), (5, 'Оболонський'), (6, 'Печерський'), (7, 'Подільський'), (8, 'Святошинський'), (9, 'Солом’янський'), (10, 'Шевченківський'), (11, 'Галицький'), (12, 'Залізничний'), (13, 'Личаківський'), (14, 'Сихівський'), (15, 'Франківський'), (16, 'Шевченківський'), (17, 'Холодногірський'), (18, 'Шевченківський'), (19, 'Київський'), (20, 'Салтівський'), (21, 'Немишлянський'), (22, 'Індустріальний'), (23, 'Слобідський'), (24, 'Основ’янський'), (25, 'Новобаварський'), (26, 'Київський'), (27, 'Хаджибейський'), (28, 'Приморський'), (29, 'Пересипський'), (30, 'Амур-Нижньодніпровський'), (31, 'Шевченківський'), (32, 'Соборний'), (33, 'Індустріальний'), (34, 'Центральний'), (35, 'Чечелівський'), (36, 'Новокодацький'), (37, 'Самарський'), (38, 'Заводський'), (39, 'Хортицький'), (40, 'Комунарський'), (41, 'Дніпровський'), (42, 'Олександрівський'), (43, 'Вознесенівський'), (44, 'Шевченківський'), (45, 'Замостянський'), (46, 'Лівобережний'), (47, 'Староміський'), (48, 'Придніпровський'), (49, 'Соснівський'), (50, 'Центральний'), (51, 'Пасічна'), (52, 'БАМ'), (53, 'Каскад'), (54, 'Заріччя'), (55, 'Центр'), (56, 'Дружба'), (57, 'Аляска'), (58, 'Східний'), (59, 'Сонячний'), (60, 'Новий Світ'), (61, 'Центр'), (62, 'Ювілейний'), (63, 'Боярка'), (64, 'Північний'), (65, 'Щасливий'), (66, 'Богунський'), (67, 'Корольовський'), (68, 'Зарічний'), (69, 'Ковпаківський'), (70, 'Шевченківський'), (71, 'Київський'), (72, 'Подільський'), (73, 'Деснянський'), (74, 'Новозаводський'), (75, 'Фортечний'), (76, 'Подільський'), (77, 'Центр'), (78, 'Затишний'), (79, 'Першотравневий'), (80, 'Садгірський'), (81, 'Шевченківський'), (82, 'Центральний'), (83, 'Минайський'), (84, 'Боздоський'), (85, 'Радванський'), (86, 'Центральний'), (87, 'Зарічний'), (88, 'Староміський'), (89, 'Новоплановський'), (90, 'Баглійський'), (91, 'Дніпровський'), (92, 'Заводський'), (93, 'Центральний'), (94, 'Мікрорайон Південний'), (95, 'Мікрорайон Північний'), (96, 'Центральний'), (97, 'Південний'), (98, 'Північний'), (99, 'Дніпровський'), (100, 'Суворовський'), (101, 'Корабельний'), (102, 'Центральний'), (103, 'Заводський'), (104, 'Інгульський'), (105, 'Корабельний'), (106, 'Центральний'), (107, 'Південно-Західний')], null=True), blank=True, default=list, size=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Фітнес / Тренажерний зал'), (2, 'Біг / Легка атлетика'), (3, 'Йога / Медитація'), (4, 'Велоспорт'), (5, 'Командні види спорту'), (6, 'Бойові мистецтва'), (7, 'Походи / Гори'), (8, 'Музика / Гра на інструментах'), (9, 'Фотографія / Відео'), (10, 'Малювання / Дизайн'), (11, 'Рукоділля / DIY'), (12, 'Письменництво / Блогінг'), (13, 'Відеоігри'), (14, 'Настільні ігри'), (15, 'Кіно та Серіали'), (16, 'Аніме / Манга'), (17, 'Книги / Література'), (18, 'Кулінарія / Випічка'), (19, 'Подорожі / Туризм'), (20, 'Домашні тварини'), (21, 'Кімнатні рослини'), (22, 'Волонтерство'), (23, 'Технології / Програмування'), (24, 'Вивчення мов'), (25, 'Мода / Стиль')]), blank=True, default=list, size=10),
        ),
        migrations.CreateModel(
            name='UserPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cleanliness', 'Охайність'), ('hobbies', 'Хобі'), ('smoking', 'Ставлення до паління'), ('partying', 'Ставлення до вечірок'), ('schedule', 'Графік дня'), ('sleep_schedule', 'Режим сну'), ('political_view', 'Політичні погляди'), ('extra_intro_version', 'Інтро/екстраверсія'), ('vibe', 'Загальний вайб')], max_length=30), blank=True, default=list, size=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_priority',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Очікує обрахунку'), ('done', 'Розраховано'), ('skipped', 'Пропущено (hard filter / неповна анкета)'), ('error', 'Помилка')], default='pending', max_length=10)),
                ('hard_filter_passed', models.BooleanField(default=False)),
                ('skip_reason', models.CharField(blank=True, max_length=50)),
                ('score_vibe', models.FloatField(blank=True, null=True)),
                ('score_hobbies', models.FloatField(blank=True, null=True)),
                ('score_cleanliness', models.FloatField(blank=True, null=True)),
                ('score_smoking', models.FloatField(blank=True, null=True)),
                ('score_partying', models.FloatField(blank=True, null=True)),
                ('score_political', models.FloatField(blank=True, null=True)),
                ('score_personality', models.FloatField(blank=True, null=True)),
                ('score_schedule', models.FloatField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_result',
                'indexes': [models.Index(fields=['user_1', 'total_score'], name='match_resul_user_1__39bced_idx'), models.Index(fields=['user_2', 'total_score'], name='match_resul_user_2__d2ca4c_idx'), models.Index(fields=['is_stale'], name='match_resul_is_stal_df232d_idx')],
                'unique_together': {('user_1', 'user_2')},
            },
        ),
    ]
