# Generated by Django 5.2.7 on 2026-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_embedding_hobbies_and_more'),
        ('user', '0004_expand_hobbies_and_custom_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parsed_sleep_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parsed_wake_hour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
