# Generated by Django 5.2.7 on 2026-05-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userpriority_matchresult_and_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.CharField(choices=[('free', 'Безкоштовний'), ('p25', 'Пакет 25'), ('p45', 'Пакет 45'), ('p55', 'Пакет 55'), ('premium', 'Преміум (безліміт)')], default='premium', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
