# Generated by Django 5.2.7 on 2026-05-10 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_package_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='user.matchresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seen_profile',
                'indexes': [models.Index(fields=['user', 'seen_at'], name='seen_profil_user_id_e5f51c_idx')],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
