# Generated by Django 5.2.7 on 2026-05-10 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_seenprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_like',
                'indexes': [models.Index(fields=['from_user'], name='user_like_from_us_cf195f_idx'), models.Index(fields=['to_user'], name='user_like_to_user_e7e254_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_matches_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_matches_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_match',
                'indexes': [models.Index(fields=['user_1'], name='user_match_user_1__109d9f_idx'), models.Index(fields=['user_2'], name='user_match_user_2__f632d8_idx')],
                'unique_together': {('user_1', 'user_2')},
            },
        ),
    ]
