# Generated by Django 5.2.7 on 2026-05-26 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userpriority_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=12, unique=True)),
                ('amount_expected', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('expired', 'Прострочено')], default='pending', max_length=10)),
                ('package', models.CharField(choices=[('free', 'Безкоштовний'), ('p25', 'Пакет 25'), ('p45', 'Пакет 45'), ('p55', 'Пакет 55'), ('premium', 'Преміум (безліміт)')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('profile_unlock', 'Розблокування анкети')], default='profile_unlock', max_length=20)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='user.matchresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_order',
            },
        ),
        migrations.CreateModel(
            name='ProfileUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('active', 'Активне (розблоковано)'), ('refunded', 'Повернуто')], default='pending', max_length=10)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_profiles', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='user.matchresult')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_unlock', to='user.paymentorder')),
            ],
            options={
                'db_table': 'profile_unlock',
                'indexes': [models.Index(fields=['buyer', 'status'], name='profile_unl_buyer_i_b366b4_idx')],
                'unique_together': {('buyer', 'match')},
            },
        ),
    ]
