# Generated by Django 5.2.7 on 2026-08-07 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_unmatchedpayment_alter_user_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProfileDeletionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('reason_code', models.CharField(blank=True, choices=[('found_here', 'Знайшов/-ла buddy тут'), ('found_elsewhere', 'Знайшов/-ла buddy деінде'), ('not_useful', 'Сервіс виявився не корисним'), ('too_many_notifications', 'Забагато сповіщень'), ('privacy_concerns', 'Питання приватності'), ('technical_issues', 'Технічні проблеми'), ('other', 'Інша причина')], max_length=30, null=True)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_deletion_feedback',
                'indexes': [models.Index(fields=['reason_code'], name='profile_del_reason__c38e19_idx'), models.Index(fields=['created_at'], name='profile_del_created_fe68d0_idx')],
            },
        ),
    ]
